name: Deploy

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Redeployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          curl -X POST "https://api.vercel.com/v13/deployments" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "projectId": "'"$VERCEL_PROJECT_ID"'",
              "teamId": "'"$VERCEL_TEAM_ID"'"
            }'
