name: Deploy

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Redeployment
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_HOOK_TOKEN: ${{ secrets.VERCEL_HOOK_TOKEN }}
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_PROJECT_ID }}/${{ secrets.VERCEL_HOOK_TOKEN }}"
